timeout: '3600s'

options:
  env:
    - DOCKER_CLI_EXPERIMENTAL=enabled

steps:
  - id: buildx
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - -c
      - |
        ./build_docker.sh
