apiVersion: apps/v1
kind: Deployment
metadata:
  name: teknoir-app-cpp-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teknoir-app-cpp-template
  template:
    metadata:
      labels:
        app: teknoir-app-cpp-template
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: teknoir-app-cpp-template
          image: tekn0ir/teknoir-app-cpp:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: HMQ_SERVICE_HOST
              value: "hmq.kube-system"
            - name: HMQ_SERVICE_PORT
              value: "1883"
            - name: MQTT_IN_0
              value: "teknoir-app-cpp-template/input"
            - name: MQTT_OUT_0
              value: "teknoir-app-cpp-template/output"
