# find the Paho MQTT C++ library
set(_PAHO_MQTT_CPP_LIB_NAME libpaho-mqttpp3.a)
find_package(OpenSSL REQUIRED)

find_library(PAHO_MQTT_CPP_LIBRARIES NAMES ${_PAHO_MQTT_CPP_LIB_NAME})
unset(_PAHO_MQTT_CPP_LIB_NAME)
find_path(PAHO_MQTT_CPP_INCLUDE_DIRS NAMES mqtt/async_client.h )

add_library(PahoMqttCpp::PahoMqttCpp UNKNOWN IMPORTED)

set_target_properties(PahoMqttCpp::PahoMqttCpp PROPERTIES
    IMPORTED_LOCATION "${PAHO_MQTT_CPP_LIBRARIES}"
    INTERFACE_INCLUDE_DIRECTORIES "${PAHO_MQTT_CPP_INCLUDE_DIRS}"
    IMPORTED_LINK_INTERFACE_LANGUAGES "CPP")
if(PAHO_WITH_SSL)
    set_target_properties(PahoMqttCpp::PahoMqttCpp PROPERTIES
            INTERFACE_COMPILE_DEFINITIONS "OPENSSL=1"
            INTERFACE_LINK_LIBRARIES "OpenSSL::SSL;OpenSSL::Crypto")
endif()

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PahoMqttCpp
    REQUIRED_VARS PAHO_MQTT_CPP_LIBRARIES PAHO_MQTT_CPP_INCLUDE_DIRS)
